### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by dsheets** [janestreet/async_inotify#3]
`async_inotify` is not _unsupported_ on OS X as it compiles and installs fine there. Unfortunately, `inotify` doesn't actually support OS X and any call to `inotify` functions will result in `ENOTSUP`. This is less than ideal as `inotify` should be marked as compatible with Linux only and its presence should indicate _actual support_.

`async_inotify` is one immediate user of the `inotify` API. `async_inotify` and its users should be updated to explicitly deal with the lack of the inotify API on OS X. `inotify.2.2` will not "support" OS X and will be marked as such in opam which will cause all requiring descendents to be Linux-only.

It looks like `jenga` is the only public opam package which uses `async_inotify`. This change will probably require an update to `jenga`. What does `jenga` do on OS X?

**Comment by diml** [comment]
Jenga hasn't been tested much on OSX, but it is able to run without inotify support and it is [disabled by default on OSX](https://github.com/janestreet/jenga/blob/master/lib/system.ml#L50).

If `inotify` becomes unavailable on OSX, we'll need to add some `#ifdef` to jenga...

**Comment by sliquister** [comment]
@jeremiedimino can you close this?

- async-inotify just inherits the behavior from the underlying ocaml-inotify library, so we wouldn't make changes in async-inotify for OSX
- jenga isn't released anymore, so its use of async-inotify doesn't matter for this purpose
